store_admin_my_account:
    pattern:  /my_account
    defaults: { _controller: "ZeteqMarketBundle:StoreAdmin:my_account" }
store_admin_change_password:
    pattern:  /change_password
    defaults: { _controller: "ZeteqMarketBundle:StoreAdmin:change_password" }
store_admin_update_password:
    pattern:  /update_password
    defaults: { _controller: "ZeteqMarketBundle:StoreAdmin:update_password" }    
    
store_admin:
    pattern:  /
    defaults: { _controller: "ZeteqMarketBundle:StoreAdmin:index" }

store_admin_show:
    pattern:  /{id}/show
    defaults: { _controller: "ZeteqMarketBundle:StoreAdmin:show" }

store_admin_new:
    pattern:  /new
    defaults: { _controller: "ZeteqMarketBundle:StoreAdmin:new" }

store_admin_create:
    pattern:  /create
    defaults: { _controller: "ZeteqMarketBundle:StoreAdmin:create" }
    requirements: { _method: post }

store_admin_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ZeteqMarketBundle:StoreAdmin:edit" }

store_admin_update:
    pattern:  /{id}/update
    defaults: { _controller: "ZeteqMarketBundle:StoreAdmin:update" }
    requirements: { _method: post|put }

store_admin_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ZeteqMarketBundle:StoreAdmin:delete" }
    requirements: { _method: post|delete }


store_admin_sale_index:
    pattern:  /sale/{store_id}
    defaults: { _controller: "ZeteqMarketBundle:StoreAdmin:sale_index" }
    
store_admin_sale_edit:
    pattern:  /sale/edit/{order}{store_id}
    defaults: { _controller: "ZeteqMarketBundle:StoreAdmin:sale_edit" }
    
store_admin_sale_update:
    pattern:  /sales/update/{id}
    defaults: { _controller: "ZeteqMarketBundle:StoreAdmin:sale_update" }