home:
    pattern:  /
    defaults: { _controller: ZeteqMarketBundle:Market:index }
admin:
    pattern:  /admin
    defaults: { _controller: ZeteqMarketBundle:Admin:admin }
store_show:
    pattern:  /store/{slug}
    defaults: { _controller: "ZeteqMarketBundle:Market:show_store" }

store_info_show:
    pattern:  /store/info/{slug}
    defaults: { _controller: "ZeteqMarketBundle:Market:show_store_info" }
product_show:
    pattern:  /product/{slug}
    defaults: { _controller: "ZeteqMarketBundle:Market:show_product" }

storecategory_show:
    pattern:  /store_category/{slug}
    defaults: { _controller: "ZeteqMarketBundle:Market:show_storecategory" }
    
page_show:
    pattern:  /store/{store_slug}/page-show/{slug}
    defaults: { _controller: "ZeteqMarketBundle:Market:show_page" }
 
storesection_show:
    pattern:  /store_sections/{slug}
    defaults: { _controller: "ZeteqMarketBundle:Market:show_storesection" }
productcategory_show:
    pattern:  /category/{slug}
    defaults: { _controller: "ZeteqMarketBundle:Market:show_productcategory" }

storeproductcategory_show:
    pattern:  /store_product_category/{slug}
    defaults: { _controller: "ZeteqMarketBundle:Market:show_storeproductcategory" }
    
product_rating_submit:
    pattern:  /product/submit/product_rating_submit
    defaults: { _controller: "ZeteqMarketBundle:Market:product_rating_submit" }
    
search:
    pattern:  /search/
    defaults: { _controller: "ZeteqMarketBundle:Market:search" }