

    
    
myaccount:
    pattern:  /myaccount
    defaults: { _controller: "ZeteqFrontBundle:MyAccount:index" }
    
myaccount_edit_shipping_address:
    pattern:  /myaccount/edit_shipping_address
    defaults: { _controller: "ZeteqFrontBundle:MyAccount:edit_shipping_address" }
myaccount_update_shipping_address:
    pattern:  /myaccount/update_shipping_address
    defaults: { _controller: "ZeteqFrontBundle:MyAccount:update_shipping_address" }
    
myaccount_edit_billing_address:
    pattern:  /myaccount/edit_billing_address
    defaults: { _controller: "ZeteqFrontBundle:MyAccount:edit_billing_address" }
myaccount_update_billing_address:
    pattern:  /myaccount/update_billing_address
    defaults: { _controller: "ZeteqFrontBundle:MyAccount:update_billing_address" }


myaccount_register:
    pattern:  /customer_register
    defaults: { _controller: "ZeteqFrontBundle:MyAccount:register" }
myaccount_register_success:
    pattern:  /customer_register_success
    defaults: { _controller: "ZeteqFrontBundle:MyAccount:register_success" }
myaccount_registersave:
    pattern:  /customer_registersave
    defaults: { _controller: "ZeteqFrontBundle:MyAccount:registersave" }
myaccount_activate_user:
    pattern:  /activate_customer/{rand_string}
    defaults: { _controller: "ZeteqFrontBundle:MyAccount:activate_user" }
myaccount_reset_password:
    pattern:  /myaccount/reset_password
    defaults: { _controller: "ZeteqFrontBundle:MyAccount:reset_password" }
